### ISSUE TITLE
ERC-6909 based NFT minter

### ISSUE THREAD

**Issue by hieronx** [centrifuge/protocol-v3#3]
We'd like to use ERC6909 to mint non-fungible tokens representing individual real-world assets.

Why not ERC721: This is very expensive wrt gas, since it requires deploying a new contract for each individual asset. We can still support ERC721 tokens by building an ERC6909-wrapper of ERC721.

https://github.com/Uniswap/v4-core/blob/main/src/ERC6909.sol can be used as the base implementation, with the addition of support for https://eips.ethereum.org/EIPS/eip-6909#content-uri-extension (to support NFT metadata)

Open questions:
- [ ] 1 global ERC6909 contract, or 1 per `msg.sender` (aka 1 per minter), or 1 per pool?
- [ ] Should we add custom lock/unlock methods such that the NFT can stay in the possession of the fund manager's wallet, while being locked in the protocol?

**Comment by wischli** [comment]
Closed by #3

**Comment by lemunozm** [comment]
It's still pending the lock/unlock mechanism for this (point 2). Which should be the NFT escrow: https://github.com/centrifuge/pools-internal/pull/22
