### ISSUE TITLE
Pool registry

### ISSUE THREAD

**Issue by hieronx** [centrifuge/protocol-v3#4]
- Contains metadata
- registers pool for the first time
- `attachPool`, `attachTranche`
- Probably also `allowAsset` which dispatches `Msg.AllowAsset { assetId, ..}` from CP to CV to enable investors on CV to subscribe with `assetId`
- Store currency as address defined in https://eips.ethereum.org/EIPS/eip-7726#special-addresses

**Comment by wischli** [comment]
Can reuse some from https://github.com/centrifuge/asset-pools/commit/645b2a68d865ebbcdfe3aabcd5485ca87bad59aa

**Comment by wischli** [comment]
Closed by #33, #43 and #44
